import { SCUser, StreamItem, SystemPlaylist, Track, UserPlaylist } from "@/utils/types"

export const user = {
  avatar_url: "https://i1.sndcdn.com/avatars-OQNGzHzVoOPkhX15-znhjbA-large.jpg",
  city: "Tây Ninh",
  comments_count: 0,
  country_code: "VN",
  created_at: new Date("2021-11-05T07:55:38Z"),
  creator_subscriptions: [
    {
      product: {
        id: "free",
      },
    },
  ],
  creator_subscription: {
    product: {
      id: "free",
    },
  },
  description: "",
  followers_count: 320,
  followings_count: 675,
  first_name: "Lê Thanh Phong",
  full_name: "Lê Thanh Phong",
  groups_count: 0,
  id: 1048282486,
  kind: "user",
  last_modified: new Date("2025-10-23T19:32:16Z"),
  last_name: "",
  likes_count: 1875,
  playlist_likes_count: 7,
  permalink: "fonglee_uwu",
  permalink_url: "https://soundcloud.com/fonglee_uwu",
  playlist_count: 2,
  reposts_count: null,
  track_count: 7,
  uri: "https://api.soundcloud.com/users/soundcloud%3Ausers%3A1048282486",
  urn: "soundcloud:users:1048282486",
  username: "Fonglee",
  verified: false,
  visuals: {
    urn: "soundcloud:users:1048282486",
    enabled: true,
    visuals: [
      {
        urn: "soundcloud:visuals:228465900",
        entry_time: 0,
        visual_url: "https://i1.sndcdn.com/visuals-001048282486-x9PrAF-original.jpg",
      },
    ],
    tracking: null,
  },
  badges: {
    pro: false,
    creator_mid_tier: false,
    pro_unlimited: false,
    verified: false,
  },
  station_urn: "soundcloud:system-playlists:artist-stations:1048282486",
  station_permalink: "artist-stations:1048282486",
  date_of_birth: null,
} as SCUser

export const track = {
  artwork_url: "https://i1.sndcdn.com/artworks-IyxrPn06CAX5fx22-j8XD7w-large.jpg",
  caption: "DUALITY is OUT NOW! ☯",
  commentable: true,
  comment_count: 59,
  created_at: new Date("2021-12-10T19:04:12Z"),
  description:
    "A love letter to the dubstep of the mid 2010's, Duality is OUT NOW on @the-diversemusic :) Hope you guys dig this one! Free download link at the 'BUY' link!",
  downloadable: false,
  download_count: 0,
  duration: 260088,
  full_duration: 260075,
  embeddable_by: "all",
  genre: "Dubstep",
  has_downloads_left: false,
  id: 1175636710,
  kind: "track",
  label_name: "The Diverse",
  last_modified: new Date("2021-12-13T21:55:59Z"),
  license: "all-rights-reserved",
  likes_count: 738,
  permalink: "duality",
  permalink_url: "https://soundcloud.com/jonzomusic/duality",
  playback_count: 32671,
  public: true,
  publisher_metadata: {
    id: 1175636710,
    urn: "soundcloud:tracks:1175636710",
    album_title: "Duality",
    contains_music: true,
  },
  purchase_title: null,
  purchase_url: "https://music.the-diverse.com/Duality",
  release_date: new Date("2021-12-08T00:00:00Z"),
  reposts_count: 42,
  secret_token: null,
  sharing: "public",
  state: "finished",
  streamable: true,
  tag_list:
    '"The Diverse" "Diversity Records" NCS "Gaming Music" "No Copyright Music" "No Copyright" Teminite "Melodic Dubstep" Brostep Headbanger "Virtual Riot" "Dance & EDM" Electronic',
  title: "Duality",
  uri: "https://api.soundcloud.com/tracks/soundcloud%3Atracks%3A1175636710",
  urn: "soundcloud:tracks:1175636710",
  user_id: 60858150,
  visuals: null,
  waveform_url: "https://wave.sndcdn.com/2DWJ3WOVM5EH_m.json",
  display_date: new Date("2021-12-10T19:04:12Z"),
  media: {
    transcodings: [
      {
        url: "https://api-v2.soundcloud.com/media/soundcloud:tracks:1175636710/5dc31f35-b018-41ff-be7a-9b1b3ff67539/stream/hls",
        preset: "aac_160k",
        duration: 260088,
        snipped: false,
        format: {
          protocol: "hls",
          mime_type: 'audio/mp4; codecs="mp4a.40.2"',
        },
        quality: "sq",
        is_legacy_transcoding: false,
      },
      {
        url: "https://api-v2.soundcloud.com/media/soundcloud:tracks:1175636710/aa15e58e-6fa6-4046-b3ec-833058b5fc34/stream/hls",
        preset: "abr_sq",
        duration: 260088,
        snipped: false,
        format: {
          protocol: "hls",
          mime_type: "audio/mpegurl",
        },
        quality: "sq",
        is_legacy_transcoding: false,
      },
      {
        url: "https://api-v2.soundcloud.com/media/soundcloud:tracks:1175636710/8b2256ba-46cc-4592-a923-459bbb689957/stream/hls",
        preset: "mp3_0_1",
        duration: 260075,
        snipped: false,
        format: {
          protocol: "hls",
          mime_type: "audio/mpeg",
        },
        quality: "sq",
        is_legacy_transcoding: true,
      },
      {
        url: "https://api-v2.soundcloud.com/media/soundcloud:tracks:1175636710/8b2256ba-46cc-4592-a923-459bbb689957/stream/progressive",
        preset: "mp3_0_1",
        duration: 260075,
        snipped: false,
        format: {
          protocol: "progressive",
          mime_type: "audio/mpeg",
        },
        quality: "sq",
        is_legacy_transcoding: true,
      },
      {
        url: "https://api-v2.soundcloud.com/media/soundcloud:tracks:1175636710/9dae9dd6-f170-4979-9ad5-bcd9658d517d/stream/hls",
        preset: "opus_0_0",
        duration: 260048,
        snipped: false,
        format: {
          protocol: "hls",
          mime_type: 'audio/ogg; codecs="opus"',
        },
        quality: "sq",
        is_legacy_transcoding: true,
      },
    ],
  },
  station_urn: "soundcloud:system-playlists:track-stations:1175636710",
  station_permalink: "track-stations:1175636710",
  track_authorization:
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJVUyIsInN1YiI6IjEyMzM1OTU2MzMiLCJyaWQiOiJmMjVkYzhiMS0xZjdkLTRjY2MtYjkzNS1hMjlkZDA1ZDUwYWUiLCJpYXQiOjE3NjMxODEwMDh9.Pevy8FfQnXUWE-vAyQg1eeUxfdGt3lASWdKPKIDj9pg",
  monetization_model: "BLACKBOX",
  policy: "MONETIZE",
  user: {
    avatar_url: "https://i1.sndcdn.com/avatars-k7zcAXDXUyCIwCx4-Otg1nQ-large.jpg",
    first_name: "",
    followers_count: 469,
    full_name: "",
    id: 60858150,
    kind: "user",
    last_modified: new Date("2025-05-22T14:03:28Z"),
    last_name: "",
    permalink: "jonzomusic",
    permalink_url: "https://soundcloud.com/jonzomusic",
    uri: "https://api.soundcloud.com/users/soundcloud%3Ausers%3A60858150",
    urn: "soundcloud:users:60858150",
    username: "Jonzo",
    verified: false,
    city: "",
    country_code: "CA",
    badges: {
      pro: false,
      creator_mid_tier: false,
      pro_unlimited: false,
      verified: false,
    },
    station_urn: "soundcloud:system-playlists:artist-stations:60858150",
    station_permalink: "artist-stations:60858150",
  },
} as Track

export const playlist = {
  artwork_url: null,
  created_at: new Date("2025-10-31T07:39:15Z"),
  description: null,
  duration: 83187767,
  embeddable_by: "all",
  genre: "",
  id: 2106278395,
  kind: "playlist",
  label_name: null,
  last_modified: new Date("2025-11-14T11:43:42Z"),
  license: "all-rights-reserved",
  likes_count: 0,
  managed_by_feeds: false,
  permalink: "kawaii-10",
  permalink_url: "https://soundcloud.com/user-507087646/sets/kawaii-10",
  public: true,
  purchase_title: null,
  purchase_url: null,
  release_date: null,
  reposts_count: 0,
  secret_token: null,
  sharing: "public",
  tag_list: "",
  title: "kawaii 10",
  uri: "https://api.soundcloud.com/playlists/soundcloud%3Aplaylists%3A2106278395",
  user_id: 977407918,
  set_type: "",
  is_album: false,
  published_at: new Date("2025-10-31T07:39:15Z"),
  display_date: new Date("2025-10-31T07:39:15Z"),
  user: {
    avatar_url: "https://i1.sndcdn.com/avatars-iBz3RNa6QBxKckor-9mcTAw-large.jpg",
    first_name: "",
    followers_count: 1,
    full_name: "",
    id: 977407918,
    kind: "user",
    last_modified: new Date("2022-08-25T08:43:50Z"),
    last_name: "",
    permalink: "user-507087646",
    permalink_url: "https://soundcloud.com/user-507087646",
    uri: "https://api.soundcloud.com/users/soundcloud%3Ausers%3A977407918",
    urn: "soundcloud:users:977407918",
    username: "nananna",
    verified: false,
    city: null,
    country_code: null,
    badges: {
      pro: false,
      creator_mid_tier: false,
      pro_unlimited: false,
      verified: false,
    },
    station_urn: "soundcloud:system-playlists:artist-stations:977407918",
    station_permalink: "artist-stations:977407918",
  },
  tracks: [
    {
      id: 2085549219,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 213313559,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 610718739,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 1031836312,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 902845345,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 912272551,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 346233126,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 830943634,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 1076578015,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1489255426,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1689062493,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 174738768,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 267329349,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1791580225,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1613599608,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1823168127,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 950014801,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2200049883,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1966882027,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1189051384,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1825392765,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1318935247,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1270713553,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 1396128388,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 1917914735,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1108763974,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1894167324,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1795161286,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1269750757,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1085582317,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 1490011312,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 465461337,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1298976865,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1897231116,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1374109966,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2197898603,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2123132328,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2042160300,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 906962311,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1254966577,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1821072711,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1938261695,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1644656976,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1363087798,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 2129401431,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1893865635,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1970460935,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1157094352,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1894180344,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1797679693,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2081573595,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2035692056,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2068908624,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2199141919,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2177584077,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1937327744,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1740440436,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 711042652,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1583863047,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1715449539,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1237973809,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1704517914,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1706528535,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1702499562,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1719753207,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1082299831,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1399560226,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 971018425,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1948508727,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1488962704,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1598509854,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2101397757,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2158410666,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2094833175,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1477435087,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1121790007,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2180506287,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 1430060041,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 2197928779,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1332422260,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2101931346,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2188978431,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1970586883,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1990600931,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1984324611,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1458738883,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1876532058,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 664183742,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1531376062,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2190684939,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1844935017,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1870495944,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2140702137,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2113364655,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 800216275,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2203300587,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1655411055,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2161611921,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1892940750,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1441126828,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 856116355,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1318473016,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 523127283,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2176532637,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2203956235,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2167590234,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 2160285612,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2195416731,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2128808127,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1021145095,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2148170508,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2157989619,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2094914664,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2163363711,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 2163980226,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2123757078,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2168650353,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2169899586,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2158902996,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2148928320,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2140769463,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2160218661,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2193607707,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2092840806,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1871938185,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1722003591,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1196979046,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1224283807,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1404567040,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 898601035,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 938182630,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1012586875,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1842834066,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1382821780,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1676653713,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 912687955,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1477644889,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1462466092,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 649504151,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1327994869,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1429473475,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1819147995,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1045634020,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 290787874,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1822351329,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 967294051,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1803718101,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1207748335,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 630495471,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1122887068,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1405268191,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1017716161,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 955301056,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 848887378,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 777220729,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1389802147,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1229201287,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2203017123,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2180282447,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2154292590,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2193633767,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1890152160,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1953653231,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2066723964,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1812463128,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1777905789,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1845519591,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2049504136,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1976516015,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1916985347,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1848184968,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2050323212,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1955248031,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1921971989,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1626565812,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1268980240,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1412829646,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1109800900,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 888139351,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 576732192,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2030517672,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1466178700,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 873160885,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 411037719,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1032497947,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 495215448,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 406990881,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 576767292,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1664595663,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 495000051,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1746965496,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1313462125,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 411040287,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2153577414,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1674908736,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1699269459,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1815558165,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 206557370,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1971086599,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1976674903,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2093902389,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2089207665,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 717199354,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 845303434,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1755121620,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1834687704,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1506103717,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 539918799,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1869921372,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1783068408,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2083630830,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2108098074,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1763117268,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2077644544,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1972756623,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2084270646,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1897086642,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1892994462,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1993554687,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1923363158,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1849011345,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2147848947,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2093898660,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2127508176,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1690387581,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1992070015,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1405467739,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1965873527,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2003098463,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1280848900,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1993552607,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1841304285,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1842675969,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1806729048,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1753838766,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2041874316,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1897673712,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1769725188,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1920748964,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1835701065,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1930299557,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2207961823,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2182103155,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1592530215,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1943673063,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2182673151,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2176123713,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2158032663,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2121047745,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2194270343,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2175294894,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2081937102,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2207972727,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2172134328,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2182648243,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2208677576,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2199329739,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2198417575,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2204682471,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2209096328,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2030960748,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 785787046,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 888779725,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 246827905,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 363839357,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 386702876,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 949242736,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1070860576,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1470917080,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1483491496,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1400558308,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 1565185234,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1645369302,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1470560428,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1824070176,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 1773668853,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2030017816,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1291454860,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2013186199,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 1976246879,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2079530310,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1218046126,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 1570486564,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1497883063,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2026018508,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2209038374,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2148948681,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2200225383,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 2173596993,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2203788839,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 751477741,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2109181374,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2012332259,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1100284033,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1549838893,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 2140072578,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2161981482,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1651197441,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1994072955,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2041854456,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1966536547,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1964544323,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1935784931,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1938183164,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 2170924812,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1619167989,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1449379321,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1487278552,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1511265067,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1996592503,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2200486603,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2203164079,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 321611401,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2153358342,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 1805166165,
      kind: "track",
      monetization_model: "NOT_APPLICABLE",
      policy: "ALLOW",
    },
    {
      id: 2062187708,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2167470078,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1807178973,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2140062393,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2165235369,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1715187123,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2153818080,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2165235363,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1437185380,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2153318043,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2116773615,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2070969192,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2044269128,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2122107114,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2070969960,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1918194095,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2159193249,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1936150928,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1857452157,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2140374234,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2137945770,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1983573383,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2081066574,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1868045823,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 703323214,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1695043905,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2204507539,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2123634864,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2127593160,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1858565412,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2211968069,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 2190496923,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
    {
      id: 1990532399,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2060949900,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 2022221469,
      kind: "track",
      monetization_model: "AD_SUPPORTED",
      policy: "MONETIZE",
    },
    {
      id: 1590017651,
      kind: "track",
      monetization_model: "BLACKBOX",
      policy: "MONETIZE",
    },
  ],
  track_count: 356, // ive deleted some so mismatch
} as UserPlaylist

export const systemPlaylist = {
  urn: "soundcloud:system-playlists:artist-stations:1079866894",
  query_urn: null,
  permalink: "artist-stations:1079866894",
  permalink_url: "https://soundcloud.com/discover/sets/artist-stations:1079866894",
  title: "N_dog (2)",
  description: "Based on N_dog (2)",
  short_title: "N_dog (2)",
  short_description: "Artist station",
  tracking_feature_name: "artist-stations",
  playlist_type: "ARTIST_STATION",
  last_updated: null,
  artwork_url:
    "https://al.sndcdn.com/labs-a461adfb-0-t500x500.jpg?q=YXJ0d29ya190eXBlOiBTVEFUSU9OCnVybnM6ICJzb3VuZGNsb3VkOnVzZXJzOjEwNzk4NjY4OTQiCnVybnM6ICJzb3VuZGNsb3VkOnVzZXJzOjgxMjE5OTM4Igp1cm5zOiAic291bmRjbG91ZDp1c2Vyczo4MDg5MzUwNjQiCnVybnM6ICJzb3VuZGNsb3VkOnVzZXJzOjIzNTEyODQ3NyIKdXJuczogInNvdW5kY2xvdWQ6dXNlcnM6MTI0NzUwODMxMCIKdXJuczogInNvdW5kY2xvdWQ6dXNlcnM6OTc1NDQxMzcwIgo%3D",
  calculated_artwork_url:
    "https://al.sndcdn.com/labs-a461adfb-0-t500x500.jpg?q=YXJ0d29ya190eXBlOiBTVEFUSU9OCnVybnM6ICJzb3VuZGNsb3VkOnVzZXJzOjEwNzk4NjY4OTQiCnVybnM6ICJzb3VuZGNsb3VkOnVzZXJzOjgxMjE5OTM4Igp1cm5zOiAic291bmRjbG91ZDp1c2Vyczo4MDg5MzUwNjQiCnVybnM6ICJzb3VuZGNsb3VkOnVzZXJzOjIzNTEyODQ3NyIKdXJuczogInNvdW5kY2xvdWQ6dXNlcnM6MTI0NzUwODMxMCIKdXJuczogInNvdW5kY2xvdWQ6dXNlcnM6OTc1NDQxMzcwIgo%3D",
  likes_count: 0,
  seed: { urn: "soundcloud:users:1079866894", permalink: "/bowncat" },
  tracks: [
    { id: 1868491557, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1889208243, kind: "track", monetization_model: "NOT_APPLICABLE", policy: "ALLOW" },
    { id: 1845519591, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 382457549, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1935992888, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1823168127, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1891949415, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1931610248, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 967294051, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1889386506, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 630981939, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1290300067, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1735336248, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 650050301, kind: "track", monetization_model: "NOT_APPLICABLE", policy: "ALLOW" },
    { id: 890851030, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1976516015, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1490121277, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1332796564, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1345589104, kind: "track", monetization_model: "NOT_APPLICABLE", policy: "ALLOW" },
    { id: 1890152160, kind: "track", monetization_model: "NOT_APPLICABLE", policy: "ALLOW" },
    { id: 2094322497, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1911034697, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 2160197652, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 2112651867, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1151058964, kind: "track", monetization_model: "NOT_APPLICABLE", policy: "ALLOW" },
    { id: 1912550780, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 276148534, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 579570453, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1771387404, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1290285907, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1930978520, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1455323698, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 2182804115, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1210766836, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 250832313, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1874647977, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 975697522, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1814645271, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 2158328904, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1495424764, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1983921835, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1346086945, kind: "track", monetization_model: "NOT_APPLICABLE", policy: "ALLOW" },
    { id: 528017343, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 2077598512, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 489530925, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 323701461, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 231665051, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1280848900, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1877927988, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
    { id: 1328817205, kind: "track", monetization_model: "BLACKBOX", policy: "MONETIZE" },
  ],
  is_public: true,
  made_for: null,
  user: {
    avatar_url: "https://i1.sndcdn.com/avatars-69H9MhsAT5XDDltu-1X6yHw-large.jpg",
    first_name: "",
    followers_count: 2373839,
    full_name: "",
    id: 193,
    kind: "user",
    last_modified: new Date("2025-10-17T15:47:43Z"),
    last_name: "",
    permalink: "soundcloud",
    permalink_url: "https://soundcloud.com/soundcloud",
    uri: "https://api.soundcloud.com/users/soundcloud%3Ausers%3A193",
    urn: "soundcloud:users:193",
    username: "SoundCloud",
    verified: true,
    city: "NY / LA",
    country_code: "US",
    badges: { pro: false, creator_mid_tier: false, pro_unlimited: true, verified: true },
    station_urn: "soundcloud:system-playlists:artist-stations:193",
    station_permalink: "artist-stations:193",
  },
  kind: "system-playlist",
  id: "soundcloud:system-playlists:artist-stations:1079866894",
} as SystemPlaylist

export const trackRepost = {
  created_at: new Date("2025-11-14T22:56:40Z"),
  type: "track",
  user: {
    avatar_url: "https://i1.sndcdn.com/avatars-7FCZZ7eE5VDklJPE-abiPew-large.jpg",
    first_name: "The",
    followers_count: 5094,
    full_name: "The Bois",
    id: 278435762,
    kind: "user",
    last_modified: new Date("2025-11-08T21:56:38Z"),
    last_name: "Bois",
    permalink: "sadbois_official",
    permalink_url: "https://soundcloud.com/sadbois_official",
    uri: "https://api.soundcloud.com/users/soundcloud%3Ausers%3A278435762",
    urn: "soundcloud:users:278435762",
    username: "SadBois",
    verified: false,
    city: "Long Island NY",
    country_code: null,
    badges: {
      pro: false,
      creator_mid_tier: false,
      pro_unlimited: true,
      verified: false,
    },
    station_urn: "soundcloud:system-playlists:artist-stations:278435762",
    station_permalink: "artist-stations:278435762",
  },
  uuid: "25",
  caption:
    "If you're coming over from Tik-Tok, https://test.com/ @tewt welcome to the family! 🦋sssssssssssssssssssssssss🦋sssssssssssssssssssssssss🦋sssssssssssssssssssssssss🦋sssssssssssssssssssssssss🦋sssssssssssssssssssssssss🦋sssssssssssssssssssssssss",
  track,
} as StreamItem
