// Private soundcloud types, Generated by quicktype
// https://app.quicktype.io

export interface TrackLike {
  created_at: Date
  kind: "like"
  track: Track
}

export type Kind = "track" | "playlist" | "system-playlist" | "user"

export interface WithKind<T extends Kind = Kind> {
  kind: T
}

export interface PartialTrack extends WithKind<"track"> {
  id: number
  monetization_model: MonetizationModel
  policy: Policy
}

export interface Track extends PartialTrack {
  artwork_url: null | string
  caption: null | string
  commentable: boolean
  comment_count: number | null
  created_at: Date
  description: null | string
  downloadable: boolean
  download_count: number | null
  duration: number // will be affected by SNIP
  full_duration: number // will not be affected by POLICY
  embeddable_by: EmbeddableBy
  genre: null | string
  has_downloads_left: boolean
  label_name: null | string
  last_modified: Date
  license: License
  likes_count: number | null
  permalink: string
  permalink_url: string
  playback_count: number | null
  public: boolean
  publisher_metadata: PublisherMetadata | null
  purchase_title: null | string
  purchase_url: null | string
  release_date: Date | null
  reposts_count: number
  secret_token: null
  sharing: Sharing
  state: State
  streamable: boolean
  tag_list: string
  title: string
  uri: string
  urn: string
  user_id: number
  visuals: Visuals | null
  waveform_url: string
  display_date: Date
  media: Media
  station_urn: string
  station_permalink: string
  track_authorization: string
  user: User
}

export type EmbeddableBy = "all" | "me"

export type License = "all-rights-reserved" | "cc-by-nc-sa" | "cc-by" | "cc-by-nc"

export interface Media {
  transcodings: Transcoding[]
}

export interface Transcoding {
  url: string
  preset: Preset
  duration: number // in millis
  snipped: boolean
  format: Format
  quality: Quality
  is_legacy_transcoding: boolean
}

export interface Format {
  protocol: Protocol
  mime_type: MIMEType
}

export type MIMEType =
  | 'audio/mp4; codecs="mp4a.40.2"'
  | "audio/mpegurl"
  | "audio/mpeg"
  | 'audio/ogg; codecs="opus"'

export type Protocol = "hls" | "progressive" | "ctr-encrypted-hls" | "cbc-encrypted-hls" // TODO: Encrypted HLS currently not supported

export const PRESET_ORDER = [
  // Non-legacy transcodings
  "aac_256k",
  "aac_160k",
  "abr_sq",
  // "abr_hq", is there an option?
  // Legacy transcodings (being removed soom: https://developers.soundcloud.com/blog/api-streaming-urls)
  "mp3_1_0",
  "opus_0_0",
  "mp3_0_1",
  "mp3_standard",
  "mp3_0_0",
] as const

export type Preset = (typeof PRESET_ORDER)[number]

export type Quality = "sq" | "hq" // sq and hq makes no difference, only affects aac it seems

export type MonetizationModel = "NOT_APPLICABLE" | "AD_SUPPORTED" | "BLACKBOX"

export type Policy = "ALLOW" | "SNIP" | "BLOCK" | "MONETIZE" // Monetize is unknown

export interface PublisherMetadata {
  id: number
  urn: string
  artist?: string
  contains_music?: boolean
  publisher?: string
  isrc?: string
  explicit?: boolean
  writer_composer?: string
  album_title?: string
  p_line?: string
  p_line_for_display?: string
  release_title?: string
  iswc?: string
  upc_or_ean?: string
  c_line?: string
  c_line_for_display?: string
}

export type Sharing = "public" | "private"

export type State = "finished"

export interface SCUser extends WithKind<"user"> {
  avatar_url: string
  city: null | string
  comments_count: number
  country_code: null | string
  created_at: Date
  creator_subscriptions: Subscription[]
  creator_subscription: Subscription
  description: null | string
  followers_count: number
  followings_count: number
  first_name: string
  full_name: string
  groups_count: number
  id: number
  last_modified: Date
  last_name: string
  likes_count: number
  playlist_likes_count: number
  permalink: string
  permalink_url: string
  playlist_count: number
  reposts_count: number | null
  track_count: number
  uri: string
  urn: string
  username: string
  verified: boolean
  visuals: Visuals
  badges: Badges
  station_urn: string
  station_permalink: string
  date_of_birth: null
}

export interface Subscription {
  product: Product
}

export interface Product {
  id: ID
}

export type ID = "creator-pro-unlimited" | "free" | "creator-creator-mid-tier" | "creator-mid-tier"

export interface User extends WithKind<"user"> {
  avatar_url: string
  first_name: string
  followers_count: number
  full_name: string
  id: number
  last_modified: Date
  last_name: string
  permalink: string
  permalink_url: string
  uri: string
  urn: string
  username: string
  verified: boolean
  city: null | string
  country_code: null | string
  badges: Badges
  station_urn: string
  station_permalink: string
}

export interface Badges {
  pro: boolean
  creator_mid_tier: boolean
  pro_unlimited: boolean
  verified: boolean
}

export interface Visuals {
  urn: string
  enabled: boolean
  visuals: Visual[]
  tracking: null
}

export interface Visual {
  urn: string
  entry_time: number
  visual_url: string
}

interface PlaylistLikeBase {
  created_at: Date
  type: PlaylistLikeType
  user: User
  uuid: string
  caption: null | string
  playlist?: UserPlaylist
  system_playlist?: SystemPlaylist
}

export type PlaylistLike = PlaylistLikeBase &
  (
    | { playlist: UserPlaylist; system_playlist?: never }
    | { system_playlist: SystemPlaylist; playlist?: never }
  )

export interface BasePlaylist {
  id: number | string
  title: string
  tracks?: PartialTrack[]
}

export interface ExactPlaylist extends BasePlaylist {
  tracks: Track[]
}

export class LocalPlaylist {
  id: string
  title: string
  tracks: Track[] = []

  constructor(name: string) {
    this.id = name
    this.title = name
  }
}

export enum SetType {
  Album = "album",
  Compilation = "compilation",
  Empty = "",
  Ep = "ep",
  Single = "single",
}

export interface UserPlaylist extends BasePlaylist, WithKind<"playlist"> {
  artwork_url: null | string
  created_at: Date
  duration: number
  id: number
  last_modified: Date
  likes_count: number
  managed_by_feeds: boolean
  permalink: string
  permalink_url: string
  public: boolean
  reposts_count: number
  secret_token: null
  sharing: Sharing
  title: string
  track_count: number
  uri: string
  user_id: number
  set_type: SetType
  is_album: boolean
  published_at: Date | null
  release_date: Date | null
  display_date: Date
  user: User
  tracks?: PartialTrack[]
}

export interface SystemPlaylist extends BasePlaylist, WithKind<"system-playlist"> {
  urn: string
  query_urn: null | string
  permalink: string
  permalink_url: string
  title: string
  description: string
  short_title: string
  short_description: null | string
  tracking_feature_name: TrackingFeatureName
  playlist_type: PlaylistType
  last_updated: Date | null
  artwork_url: string
  calculated_artwork_url: string
  likes_count: number
  seed: Seed | null
  tracks: PartialTrack[]
  is_public: boolean
  made_for: User | null
  user: User
  id: string
}

export type TrackingFeatureName =
  | "artist-stations"
  | "track-stations"
  | "liked-by"
  | "new-for-you"
  | "personalized-tracks"
  | "weekly"
  | "your-moods"

export type PlaylistType = "PLAYLIST" | "TRACK_STATION" | "ARTIST_STATION"

export interface Seed {
  urn: string
  permalink: string
}

export type PlaylistLikeType = "playlist-like" | "system-playlist-like"

export interface BaseCollection<T> {
  collection: T[]
}

export interface PartitionedCollection<T> extends BaseCollection<T> {
  next_href: string | null
  query_urn: string | null
}

export const SOCIAL_NETWORKS = {
  bandpage: "BandPage",
  bandcamp: "Bandcamp",
  bandsintown: "Bandsintown",
  beatport: "Beatport",
  berklee: "Berklee",
  ccmixter: "ccMixter",
  discogs: "Discogs",
  facebook: "Facebook",
  flavors: "flavors.me",
  flickr: "Flickr",
  foursquare: "Foursquare",
  freesound: "Freesound",
  gigatools: "Gigatools",
  google_plus: "Google+",
  hypem: "Hype Machine",
  instagram: "Instagram",
  itunes_podcast: "iTunes Podcast",
  lastfm: "Last.fm",
  linktree: "Linktree",
  mixcloud: "Mixcloud",
  myspace: "MySpace",
  ning: "Ning",
  pinterest: "Pinterest",
  purevolume: "PureVolume",
  residentadvisor: "Resident Advisor",
  residentadvisorlabel: "Resident Advisor",
  reverbnation: "ReverbNation",
  snapchat: "Snapchat",
  songkick: "Songkick",
  soundcloud: "SoundCloud",
  spotify: "Spotify",
  thedjlist: "The DJ List",
  tumblr: "Tumblr",
  twitter: "Twitter",
  vimeo: "Vimeo",
  virb: "Virb",
  vkontakte: "VK",
  whatpeopleplay: "Whatpeopleplay",
  wordpress: "Wordpress",
  youtube: "YouTube",
  zeroinch: "zero",
} as const

export interface WebProfile {
  url: string
  network: string
  title: string
  username?: string
}

export interface Comment {
  kind: "comment"
  id: number
  body: string
  created_at: Date
  timestamp: number
  track_id: number
  user_id: number
  self: Self
  user: User
  track: Track
}

export interface Self {
  urn: string
}

export interface StreamItem {
  created_at: Date
  type: StreamType
  user: User
  uuid: string
  caption: null | string
  reposted?: Reposted
  track?: Track
  playlist?: UserPlaylist
}

// activityTypes: TrackPost,TrackRepost,PlaylistPost
export type StreamType = "track" | "track-repost" | "playlist" | "playlist-repost"

export interface Reposted {
  target_urn: string
  user_urn: string
  caption: null | string
}

export interface QueryCollection<T> {
  collection: T[]
  query_urn: string
  variant: string
}

export interface Me extends WithKind<"user"> {
  avatar_url: string
  blocked_tracks_count: number
  city: string
  comments_count: number
  consumer_subscriptions: Subscription[] | null
  consumer_subscription: Subscription
  country_code: string
  cpp: null
  created_at: Date
  creator_subscriptions: Subscription[]
  creator_subscription: Subscription
  date_of_birth: DateOfBirth
  default_license: string
  default_tracks_feedable: boolean
  description: string
  downloads_disabled: boolean
  downloads_disabled_reason: string
  first_name: string
  followers_count: number
  followings_count: number
  full_name: string
  gender: string
  groups_count: number
  hidden_tracks_count: number
  id: number
  last_modified: Date
  last_name: string
  likes_count: number
  playlist_likes_count: number
  locale: string
  permalink: string
  permalink_url: string
  playlist_count: number
  primary_email: string
  primary_email_confirmed: boolean
  primary_email_sha256: string
  private_playlists_count: number
  private_tracks_count: number
  quota: Quota
  reposts_count: number
  track_count: number
  urn: string
  uri: string
  username: string
  verified: boolean
  visuals: Visuals
  confirmed: boolean
  badges: Badges
  analytics_id: null
  consent_management_jwt: ConsentManagementJwt
  station_urn: string
  station_permalink: string
  marketing_ids: MarketingIDS
  ppid: string
  spotlight_limit: number
}

export interface ConsentManagementJwt {
  userId: string
  jwt: string
}

export interface DateOfBirth {
  month: number
  year: number
  day: number
}

export interface MarketingIDS {
  gtm: string
}

export interface Quota {
  unlimited_upload_quota: boolean
  upload_seconds_limit: number
  upload_seconds_used: number
  upload_seconds_left: number
  upload_tracks_used: number
  unlimited_upload_duration_quota: boolean
  unlimited_upload_track_quota: boolean
}

export interface M3U8Info {
  url: string
  licenseUrls: unknown // an object containing playready/fairplay urls
}

// they are the same huh
export interface SearchSuggestion {
  output: string
  query: string
}

export interface FacetItem {
  name: "place" | "model" | "genre"
  facets: FacetDetail[]
}

/**
 * value (in lowercase):
 * - place: places
 * - genre: music genre
 * - model: can be set / sound / person
 */
export interface FacetDetail {
  value: string
  count: number
  filter: string // the request params (filter.<name> = <value>)
}

export interface SearchCollection<T extends Track | UserPlaylist | SCUser>
  extends PartitionedCollection<T> {
  total_results: number
  facets: FacetItem[]
}

export interface WhoToFollowResp {
  token: string
  source: Source
  user: User
}

export type Source = "algorithm"

export interface Waveform {
  width: number
  height: number
  samples: number[] // the length of samples should match width, and maximum value must match height.
}

export type LicenseFilter = "to_modify_commercially" | "to_use_commercially" | "to_share"

export type DurationFilter = "short" | "medium" | "long" | "epic"

export type CreatedAtFilter =
  | "last_hour"
  | "last_day"
  | "last_week"
  | "last_month"
  | "last_year"
  | "any_time"

export type ContentTierFilter = "SUB_HIGH_TIER"

export type GenreFilter = string
export type LocationFilter = string

export interface Selection {
  urn: string
  query_urn: string
  title: string
  description: null
  tracking_feature_name: string
  last_updated: Date | null
  style: null
  social_proof: null
  social_proof_users: null
  items: PartitionedCollection<WithKind<Kind>>
  kind: "selection"
  id: string
}

export interface UserActivity {
  user_urn: string
  unread_update_at?: Date
  has_read: boolean
  user: User
}
